// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvj-6rn4xEkn7PfHHNMbQzwTXsskKmuy0',
    appId: '1:219682843699:web:24e571b72802ba83fb4746',
    messagingSenderId: '219682843699',
    projectId: 'mhacks2023',
    authDomain: 'mhacks2023.firebaseapp.com',
    storageBucket: 'mhacks2023.appspot.com',
    measurementId: 'G-QH2699H1ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2_cprgMj4FLa-3eWfmjqFQ-xh0PBxNpI',
    appId: '1:219682843699:android:6ddb1a30509b89d9fb4746',
    messagingSenderId: '219682843699',
    projectId: 'mhacks2023',
    storageBucket: 'mhacks2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClmUDq-ivY3YxPz3b4Bb5BY8-DZayb8yo',
    appId: '1:219682843699:ios:8791e6c7f7b33f43fb4746',
    messagingSenderId: '219682843699',
    projectId: 'mhacks2023',
    storageBucket: 'mhacks2023.appspot.com',
    iosClientId: '219682843699-sk68o47ru8bi5s1cv1n5ptslpiut9lfe.apps.googleusercontent.com',
    iosBundleId: 'com.example.cameraUpload',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClmUDq-ivY3YxPz3b4Bb5BY8-DZayb8yo',
    appId: '1:219682843699:ios:5bdb369007695c01fb4746',
    messagingSenderId: '219682843699',
    projectId: 'mhacks2023',
    storageBucket: 'mhacks2023.appspot.com',
    iosClientId: '219682843699-can774ml1i0bbr65e7pf7e1g2dvtcl2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.cameraUpload.RunnerTests',
  );
}
